name: cucumber-manual-self-hosted-example

on: workflow_dispatch

jobs:
  cypress-manual-self-hosted:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      uses: cypress-io/github-action@v6
      with:
        # perform installation
        runTests: false
        install: false
        
    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: |
        echo "CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}" >> $GITHUB_ENV

    - name: Run Cypress tests
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      run: npm run cy:CucumberLogin --record --parallel

    - name: Upload Results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos